apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm-ipam
spec:
  services:
    - repo-setup
    - download-cache
    - bootstrap
    - reboot-os
    - configure-ovs-dpdk
    - configure-network
    - validate-network
    - install-os
    - configure-os
    - run-os
    - ovn
    - neutron-metadata
    - libvirt
    - nova-custom-ovsdpdk
    - telemetry

  baremetalSetTemplate:
    bmhLabelSelector:
      app: openstack
    ctlplaneInterface: ens4f0
    cloudUserName: cloud-admin
    passwordSecret:
      name: baremetalset-password-secret
      namespace: openstack

  nodes:
    #    tigon06:
    #      hostName: tigon06
    tigon19:
      hostName: tigon19
  networkAttachments:
    - ctlplane
  nodeTemplate:
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    networks:
      - name: ctlplane
        subnetName: subnet1
        defaultRoute: true
      - name: internalapi
        subnetName: subnet1
      - name: storage
        subnetName: subnet1
      - name: tenant
        subnetName: subnet1
    managementNetwork: ctlplane
    ansible:
      ansibleVars:
         edpm_network_config_os_net_config_mappings:
           #           tigon06:
           #             nic1: '80:18:44:f2:88:b0' # eno1 
           #             nic2: '80:18:44:f2:88:b1' # eno2 
           #             nic3: 'f8:f2:1e:03:61:a0' # enp130s0f0
           #             nic4: 'f8:f2:1e:03:61:a2' # enp130s0f1
           #             nic5: 'f8:f2:1e:03:61:a4' # enp130s0f2
           #             nic6: 'f8:f2:1e:03:61:a6' # enp130s0f3
           #             nic7: 'f8:f2:1e:03:c8:c0' # enp6s0f0
           #             nic8: 'f8:f2:1e:03:c8:c2' # enp6s0f1
           #             nic9: 'f8:f2:1e:03:c8:c4' # enp6s0f2
           #             nic10: 'f8:f2:1e:03:c8:c6' # enp6s0f3
           #             nic11: 'b8:3f:d2:6f:ea:60' # enp4s0f0np0
           #             nic12: 'b8:3f:d2:6f:ea:61' # enp4s0f0np1
           tigon19:
             nic1: 'e4:43:4b:48:5f:c0' # eno1
             nic2: 'e4:43:4b:48:5f:c1' # eno2
             nic3: 'f8:f2:1e:54:c9:00' # ens4f0
             nic4: 'f8:f2:1e:54:c9:01' # ens4f1
             nic5: 'f8:f2:1e:54:c9:02' # ens4f2
             nic6: 'f8:f2:1e:54:c9:03' # ens4f3
             nic7: 'f8:f2:1e:54:c1:60' # ens7f0
             nic8: 'f8:f2:1e:54:c1:61' # ens7f1
             nic9: 'f8:f2:1e:54:c1:62' # ens7f2
             nic10: 'f8:f2:1e:54:c1:63' # ens7f3
             nic11: '98:03:9b:9d:73:00' # ens6f0np0
             nic12: '98:03:9b:9d:73:01' # ens6f0np1
         edpm_network_config_template: |
           ---
           {% set mtu_list = [ctlplane_mtu] %}
           {% for network in role_networks %}
           {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
           {%- endfor %}
           {% set min_viable_mtu = mtu_list | max %}
           network_config:
           - type: ovs_bridge
             name: br-osp
             mtu: {{ min_viable_mtu }}
             use_dhcp: false
             dns_servers: {{ ctlplane_dns_nameservers }}
             domain: {{ dns_search_domains }}
             addresses:
             - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}
             routes: {{ ctlplane_host_routes }}
             members:
             - type: interface
               name: nic3
               mtu: {{ min_viable_mtu }}
               # force the MAC address of the bridge to this interface
               primary: true
           {% for network in role_networks if network not in ["External", "tenant"] %}
             - type: vlan
               mtu: {{ lookup('vars', networks_lower[network] ~ '_mtu') }}
               vlan_id: {{ lookup('vars', networks_lower[network] ~ '_vlan_id') }}
               addresses:
               - ip_netmask:
                   {{ lookup('vars', networks_lower[network] ~ '_ip') }}/{{ lookup('vars', networks_lower[network] ~ '_cidr') }}
               routes: {{ lookup('vars', networks_lower[network] ~ '_host_routes') }}
           {% endfor %}
           - type: interface
             name: nic1
             use_dhcp: false
             default: false
           - type: interface
             name: nic2
             use_dhcp: false
             default: false
           - type: ovs_user_bridge
             name: br-link1
             use_dhcp: false
             ovs_extra: "set port br-link1 tag=144"
             addresses:
             - ip_netmask: {{ lookup('vars', networks_lower['tenant'] ~ '_ip') }}/{{ lookup('vars', networks_lower['tenant'] ~ '_cidr')}}
             mtu: 9000
             members:
             - type: ovs_dpdk_port
               name: dpdk1
               members:
               - type: interface
                 name: nic4
           - type: ovs_user_bridge
             name: br-link2
             use_dhcp: false
             mtu: 9000
             members:
             - type: ovs_dpdk_port
               name: dpdk2
               members:
               - type: interface
                 name: nic5
                   #           - type: sriov_pf
                   #             name: nic5
                   #             use_dhcp: false
                   #             numvfs: 5
                   #           - type: sriov_pf
                   #             name: nic6
                   #             use_dhcp: false
                   #             numvfs: 5
         # These vars are for the network config templates themselves and are
         # considered EDPM network defaults.
         neutron_physical_bridge_name: br-access
         neutron_public_interface_name: enp6s0f1
         registry_url: quay.io/podified-antelope-centos9
         image_tag: current-podified
         image_prefix: openstack
         edpm_chrony_ntp_servers:
           - pool.ntp.org
         # edpm_nodes_validation
         edpm_nodes_validation_validate_controllers_icmp: false
         edpm_nodes_validation_validate_gateway_icmp: false
         # edpm nfv ovs dpdk config
         edpm_kernel_args: "default_hugepagesz=1GB hugepagesz=1G hugepages=64 iommu=pt intel_iommu=on tsx=off isolcpus=2-19,22-39"
         edpm_tuned_profile: "cpu-partitioning"
         edpm_tuned_isolated_cores: "2-19,22-39"
         edpm_ovs_dpdk_pmd_core_list: "2,3"
         edpm_ovs_dpdk_lcore_list: "0,20,1,21"
         edpm_ovs_dpdk_socket_memory: "4096"
         edpm_ovs_dpdk_memory_channels: "4"
         edpm_ovs_dpdk_vhost_postcopy_support: "true"
         edpm_ovn_bridge_mappings: ['access:br-access','dpdk2:br-link2','dpdk1:br-link1']
         gather_facts: false
         enable_debug: false
         edpm_nova_libvirt_qemu_group: "hugetlbfs"
         # edpm firewall, change the allowed CIDR if needed
         edpm_sshd_allowed_ranges: ['192.168.122.0/24']
